_BASE_: ../Base-Lifeplan-InstanceSegmentation.yaml
MODEL:
  META_ARCHITECTURE: "MaskDINO"
  BACKBONE:
    NAME: "D2EVA02_ViT"
  EVA:
    IMG_SIZE: 1536
    PATCH_SIZE: 16
    EMBED_DIM: 1024
    DEPTH: 24
    NUM_HEADS: 16
    MLP_RATIO: 2.6667
    QKV_BIAS: True
    DROP_PATH_RATE: 0.3
    ROPE: True
    WINDOW_SIZE: 16
    WINDOW_BLOCK_INDEXES: [ 0, 1, 3, 4, 6, 7, 9, 10, 12, 13, 15, 16, 18, 19, 21, 22 ]
    OUT_CHANNELS: 256
    XATTN: False
    USE_ACT_CHECKPOINT: True
  WEIGHTS: "eva02_L_m38m_to_o365.pth"
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  # head
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 1
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MaskDINOEncoder"
    DIM_FEEDFORWARD: 2048
    NUM_FEATURE_LEVELS: 4
    TOTAL_NUM_FEATURE_LEVELS: 5
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res2","res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
    FEATURE_ORDER: "low2high"
  MaskDINO:
    TRANSFORMER_DECODER_NAME: "MaskDINODecoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 4.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    BOX_WEIGHT: 5.0
    GIOU_WEIGHT: 2.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 300 ### SHOUDL WE PLAY WITH THIS?
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 9  # 9+1, 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    EVAL_FLAG: 1
    INITIAL_PRED: True
    TWO_STAGE: True
    DN: "seg"
    DN_NUM: 100
    INITIALIZE_BOX_TYPE: 'bitmask'
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.25
INPUT:
  IMAGE_SIZE: 1536
  MIN_SIZE_TEST: 1536
  MAX_SIZE_TEST: 1536
SOLVER:
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 2 #4 ### SET TO 4 FOR SWIN, 16 FOR R50
  BASE_LR: 0.0002
  MAX_ITER: 90000
TEST:
  EVAL_PERIOD: 1000
  DETECTIONS_PER_IMAGE: 105
#  EVAL_FLAG: 1