_wandb:
    value:
        cli_version: 0.21.3
        e:
            jexchzvgofvrjmrpqn4jt0rzknrw3d89:
                args:
                    - --num-gpus
                    - "1"
                    - --resume
                    - --exp_id
                    - "512"
                    - --config-file
                    - /home/mrajaraman/master-thesis-dragonfly/mask-DINO/MaskDINO-MassID45/configs/lifeplan/instance-segmentation/maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml
                    - --dataset_path
                    - /home/mrajaraman/dataset/coco/
                    - OUTPUT_DIR
                    - output_lifeplan_b_512_sahi_tiled_v9_R50_1024_one_cycle_lr_5e-5_colour_augs_15k_iters
                    - DATASETS.TRAIN
                    - ("dragonfly_512_train",)
                    - DATASETS.TEST
                    - ("dragonfly_512_valid",)
                codePath: mask-DINO/MaskDINO-MassID45/train_net.py
                codePathLocal: train_net.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "52521500672"
                        used: "8761503744"
                email: mrnalini@live.in
                executable: /home/mrajaraman/conda/maskdino/bin/python
                git:
                    commit: 2d140ac385db07473682749d282a28d690cfb4a3
                    remote: https://github.com/itismeganrms/master-thesis-dragonfly.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-6548872f-ccaf-cf3a-4d35-8582cf146b08
                    - architecture: Ampere
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-e0eca545-f9a0-ac61-ca69-eeaad65d2199
                host: node872
                memory:
                    total: "270301937664"
                os: Linux-5.14.0-427.33.1.el9_4.x86_64-x86_64-with-glibc2.17
                program: train_net.py
                python: CPython 3.8.20
                root: /zfsstore/user/mrajaraman/master-thesis-dragonfly/mask-DINO/MaskDINO-MassID45
                slurm:
                    cluster_name: alice
                    conf: /cm/shared/apps/slurm/var/etc/alice/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: biodiversityhotspots
                    job_cpus_per_node: "1"
                    job_end_time: "1757552807"
                    job_gid: "1442"
                    job_gpus: "1"
                    job_id: "4705815"
                    job_name: maskdino
                    job_nodelist: node872
                    job_num_nodes: "1"
                    job_partition: gpu-long
                    job_qos: normal
                    job_start_time: "1757509607"
                    job_uid: "2744"
                    job_user: mrajaraman
                    jobid: "4705815"
                    localid: "0"
                    mem_per_cpu: "4000"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: node872
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /zfsstore/user/mrajaraman/master-thesis-dragonfly/mask-DINO/MaskDINO-MassID45
                    submit_host: nodelogin01
                    task_pid: "635850"
                    tasks_per_node: "1"
                    topology_addr: node872
                    topology_addr_pattern: node
                    working_cluster: alice:mgmt2:6817:9984:109
                startedAt: "2025-09-10T13:06:54.786202Z"
                writerId: jexchzvgofvrjmrpqn4jt0rzknrw3d89
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 43
                - 49
                - 63
            "2":
                - 1
                - 41
                - 43
                - 49
                - 63
            "3":
                - 15
                - 16
                - 35
            "4": 3.8.20
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
architecture:
    value: Mask-DINO
